name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build Docker image
      run: |
        docker build -t builder docker/

    - name: Build apk
      run: |
        ./.github/workflows/build-ci.sh

    - name: Archive apk
      uses: actions/upload-artifact@v4
      with:
        name: android-release.apk
        path: android/build/outputs/apk/release/android-release.apk

    - name: Archive libs
      uses: actions/upload-artifact@v4
      with:
        name: libs
        path: flowpilot/android/libs
